name: 'ci-cd'
on:
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test

