name: 'coverage'
on: ["pull_request"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm turbo
      - name: Run unit tests coverage
        run: pnpm coverage
      - name: Upload to coveralls
        uses: coverallsapp/github-action@v1.1.2 
        with:
          # 无需自定义的 token，直接写就好，是官方给内置的 token
          github-token: ${{ secrets.GITHUB_TOKEN }}

